create table if not exists public.employee_schedules (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees(id) on delete cascade,
  work_date date not null,
  shift_type text not null check (shift_type in ('morning', 'evening', 'all_day', 'manual')),
  manual_start_time time null,
  manual_hours numeric(4,1) null,
  created_at timestamptz not null default now()
);

alter table public.employee_schedules enable row level security;

drop policy if exists "Enable select for all users" on public.employee_schedules;
create policy "Enable select for all users" on public.employee_schedules for select using (true);

drop policy if exists "Enable insert for all users" on public.employee_schedules;
create policy "Enable insert for all users" on public.employee_schedules for insert with check (true);

drop policy if exists "Enable update for all users" on public.employee_schedules;
create policy "Enable update for all users" on public.employee_schedules for update using (true) with check (true);

drop policy if exists "Enable delete for all users" on public.employee_schedules;
create policy "Enable delete for all users" on public.employee_schedules for delete using (true);

create unique index if not exists idx_employee_schedules_emp_date_unique
on public.employee_schedules (employee_id, work_date);

create index if not exists idx_employee_schedules_work_date
on public.employee_schedules (work_date);

create or replace function public.trg_employee_schedules_enforce_daily_limit()
returns trigger
language plpgsql
as $$
declare
  v_count integer;
  v_dow integer;
begin
  v_dow := extract(dow from new.work_date);

  if new.shift_type = 'manual' then
    if new.manual_start_time is null or new.manual_hours is null or new.manual_hours <= 0 then
      raise exception 'manual shift requires manual_start_time and positive manual_hours';
    end if;
  else
    new.manual_start_time := null;
    new.manual_hours := null;
  end if;

  if v_dow = 3 and new.shift_type not in ('all_day', 'manual') then
    raise exception 'wednesday must be all_day';
  end if;

  if v_dow <> 3 and new.shift_type = 'all_day' then
    raise exception 'all_day is allowed only on wednesday';
  end if;

  select count(*)
    into v_count
  from public.employee_schedules es
  where es.work_date = new.work_date
    and (tg_op <> 'UPDATE' or es.id <> old.id);

  if v_dow = 3 then
    if v_count >= 1 then
      raise exception 'daily schedule limit exceeded for %', new.work_date;
    end if;
  else
    if v_count >= 2 then
      raise exception 'daily schedule limit exceeded for %', new.work_date;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists employee_schedules_enforce_daily_limit on public.employee_schedules;
create trigger employee_schedules_enforce_daily_limit
before insert or update of work_date on public.employee_schedules
for each row execute function public.trg_employee_schedules_enforce_daily_limit();
