CREATE TABLE IF NOT EXISTS public.employee_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id UUID NOT NULL REFERENCES public.employees (id) ON DELETE CASCADE,
  shift_type TEXT NOT NULL CHECK (shift_type IN ('6AM', '9AM')),
  work_date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_employee_schedules_employee_date
ON public.employee_schedules (employee_id, work_date);

CREATE OR REPLACE FUNCTION public.fn_employee_schedules_enforce_daily_limit()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  cnt INTEGER;
BEGIN
  SELECT COUNT(*)
  INTO cnt
  FROM public.employee_schedules s
  WHERE s.work_date = NEW.work_date
    AND (TG_OP = 'INSERT' OR s.id <> NEW.id);

  IF cnt >= 2 THEN
    RAISE EXCEPTION 'Daily schedule limit reached for %', NEW.work_date;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_employee_schedules_daily_limit ON public.employee_schedules;
CREATE TRIGGER trg_employee_schedules_daily_limit
BEFORE INSERT OR UPDATE OF work_date ON public.employee_schedules
FOR EACH ROW
EXECUTE FUNCTION public.fn_employee_schedules_enforce_daily_limit();

ALTER TABLE public.employee_schedules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable select for all users" ON public.employee_schedules;
CREATE POLICY "Enable select for all users" ON public.employee_schedules FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for all users" ON public.employee_schedules;
CREATE POLICY "Enable insert for all users" ON public.employee_schedules FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable update for all users" ON public.employee_schedules;
CREATE POLICY "Enable update for all users" ON public.employee_schedules FOR UPDATE USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable delete for all users" ON public.employee_schedules;
CREATE POLICY "Enable delete for all users" ON public.employee_schedules FOR DELETE USING (true);

